schema_type: 'common'

player:
  info:
    username:
      type: 'TEXT'
    nickname:
      type: 'TEXT'

  items:
    quantity:
      type: 'INT'
      value: 1
    name:
      type: 'TEXT'
      value: 'Peanut butter pie'
    rarity:
      'type': 'INT'
      'value': 1