schema_type: 'router'

player:
  data:
    uuid:
      type: TEXT UNIQUE
      default: 'null'
      value: 'FUBAR'
    username:
      type: TEXT
      default: null
      value: 'SPINACH BUTTER STEAK'
    nickname:
      type: TEXT
      default: null



