server:
  name: 'async sqlite server'
  host: '127.0.0.1'
  port: '8080'
  http_version: 3


  endpoints:
    '/':
      methods:
        - 'HEAD'
        - 'GET'

      response:
        content:
          'Index page'

    '/db':
      methods:
        - 'OPTIONS'
        - 'GET'

      response:
        content:
          '{app.db.}'

#      '/router':
#        '/fetch':
#          methods:
#            - 'GET'
#
#        '/add':
#          methods:
#            - 'POST'
#
#        '/remove':
#          methods:
#            - 'PUT'
#            - 'PATCH'


#      '/common':
#        methods:
#          - 'GET'
#          - 'POST'

#        '/fetch_tables/':
#
#        '/table/<database:str>/<table:str>':
#          methods:
#            - 'PUT'
#            - 'PATCH'

#        '/query/<database:str>':
#          auth: 'dev'
##
#
#    '/auth':
#





database:
  base_path: 'database/'
  router_path: 'router/'
  common_path: 'common/'


